# Generated by Django 6.0.2 on 2026-03-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctorprofile_approved_by_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='doctor_id_cards/'),
        ),
    ]
