# Generated by Django 6.0.2 on 2026-03-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctorprofile_doctor_id_doctorprofile_id_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalReferenceDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('hospital_doc_id', models.CharField(max_length=20, unique=True)),
                ('specialization', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Hospital Reference Doctor',
                'verbose_name_plural': 'Hospital Reference Doctors',
                'ordering': ['name'],
            },
        ),
    ]
