# Generated by Django 6.0.1 on 2026-02-23 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_hardwareconfig_hardwarestatus'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
            ],
        ),
    ]
