# Generated by Django 6.0.1 on 2026-02-23 01:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_activemonitoring'),
        ('patients', '0002_remove_alert_priority_alert_bpm_alert_spo2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activemonitoring',
            old_name='updated_at',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='hardwarestatus',
            old_name='is_connected',
            new_name='connected',
        ),
        migrations.RemoveField(
            model_name='patientvitals',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='patientvitals',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activemonitoring',
            name='active_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='patientvitals',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
