# Generated by Django 6.0.2 on 2026-03-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_medicalreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvitals',
            name='is_seeded',
            field=models.BooleanField(default=False),
        ),
    ]
