# Generated by Django 6.0.1 on 2026-02-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='priority',
        ),
        migrations.AddField(
            model_name='alert',
            name='bpm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='spo2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(default='CRITICAL', max_length=20),
        ),
    ]
