# Generated by Django 6.0.2 on 2026-03-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_alert_priority_alert_bpm_alert_spo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_severity',
            field=models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('critical', 'Critical')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('monitoring_status', 'Monitoring Status'), ('heart_rate_warning', 'Heart Rate Warning'), ('critical_health', 'Critical Health Alert'), ('oxygen_warning', 'Oxygen Warning')], default='monitoring_status', max_length=30),
        ),
    ]
