# Generated by Django 6.0.2 on 2026-03-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_blood_group_patient_height_patient_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='condition',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Observation', 'Observation'), ('Critical', 'Critical')], default='Normal', max_length=200),
        ),
    ]
