# Generated by Django 6.0.2 on 2026-03-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_condition_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='monitoring_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
